apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "covid"
  namespace: "default"
  labels:
    app: "covid"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "covid"
  template:
    metadata:
      labels:
        app: "covid"
    spec:
      containers:
        - name: "covid-19-jhu-csse-service"
          image: "covid-19-jhu-csse-service:latest"
