apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: covid
  name: covid-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid
  template:
    metadata:
      labels:
        app: covid
        deployment: covid
    spec:
      containers:
        - image: covid-19-texas-cases-service:latest
          name: covid-container
          ports:
            - containerPort: 8080
