apiVersion: v1
kind: Service
metadata:
  labels:
    app: covid
  name: covid-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: covid
    deployment: covid
  sessionAffinity: None
  type: LoadBalancer