apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: covid
    spec:
      containers:
        - name: covid-container
          image: covid-19-texas-cases-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

